[package]
name = "emb1"
version = "0.1.0"
authors = ["cbiffle <code@cliffle.com>"]

[dependencies]
rust-libcore = "*"
embrs = { path = "embrs" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
