[package]
name = "emb1"
version = "0.1.0"
authors = ["cbiffle <code@cliffle.com>"]

[dependencies]
embrs = { path = "embrs", features = [ "soc:stm32f407" ] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
