[package]
name = "embrs"
version = "0.1.0"
authors = ["cbiffle <code@cliffle.com>"]

[dependencies]
bitflags = "0.7"

[features]
default = []

app_panic_fmt = []

"soc:stm32f407" = [
  "soc_family:stm32f4[01]",
]

"soc_family:stm32f4[01]" = ["soc_family:stm32f4"]

"soc_family:stm32f4" = []
